# Generated by Django 4.2.29 on 2026-03-22 22:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('incremento_tempo', models.IntegerField(verbose_name='Incremento de Tempo (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'servicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('incremento_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Incremento de Valor')),
                ('incremento_tempo', models.IntegerField(verbose_name='Incremento de Tempo (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'db_table': 'tamanhos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('lavador', 'Lavador')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fabricante', models.ForeignKey(db_column='fabricantes_id', on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='lavup.fabricante', verbose_name='Fabricante')),
                ('tamanho', models.ForeignKey(db_column='tamanhos_id', on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='lavup.tamanho', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('iniciada', 'Iniciada'), ('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('placa_veiculo', models.CharField(max_length=20, verbose_name='Placa do Veículo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='lavup.cliente', verbose_name='Cliente')),
                ('veiculo', models.ForeignKey(db_column='veiculos_id', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='lavup.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'ordem_servico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_previsto', models.DateTimeField(verbose_name='Início Previsto')),
                ('fim_previsto', models.DateTimeField(verbose_name='Fim Previsto')),
                ('inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Início Real')),
                ('fim_real', models.DateTimeField(blank=True, null=True, verbose_name='Fim Real')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lavador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='lavup.usuario', verbose_name='Lavador')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='lavup.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'agenda',
                'ordering': ['-inicio_previsto'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.CharField(max_length=20, verbose_name='Valor Aplicado')),
                ('tempo_aplicado', models.IntegerField(verbose_name='Tempo Aplicado (min)')),
                ('ordem_servico', models.ForeignKey(db_column='os_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='lavup.ordemservico', verbose_name='Ordem de Serviço')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='lavup.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço da OS',
                'verbose_name_plural': 'Serviços da OS',
                'db_table': 'os_servicos',
                'unique_together': {('ordem_servico', 'servico')},
            },
        ),
    ]
