# Generated by Django 4.2.29 on 2026-03-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Email ou WhatsApp do usuário bloqueado', max_length=255, unique=True, verbose_name='Identificador')),
                ('tentativas_falhas', models.IntegerField(default=0, verbose_name='Tentativas Falhas')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Bloqueio de Login',
                'verbose_name_plural': 'Bloqueios de Login',
                'db_table': 'bloqueios_login',
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacao', to='lavup.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
                'db_table': 'codigos_verificacao',
                'ordering': ['-created_at'],
            },
        ),
    ]
