# Generated by Django 4.2.29 on 2026-05-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavup', '0005_seed_admins_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='os',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='lavup.ordemservico', verbose_name='Ordem de Serviço'),
        ),
    ]
