# Generated by Django 4.2.29 on 2026-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavup', '0006_alter_agenda_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoservico',
            name='valor_aplicado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Aplicado'),
        ),
    ]
