# Generated by Django 4.2.29 on 2026-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavup', '0007_alter_ordemservicoservico_valor_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('placeholders', models.CharField(blank=True, help_text='Lista separada por vírgula dos placeholders aceitos no corpo (ex.: codigo,minutos)', max_length=255, verbose_name='Placeholders')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagens',
                'ordering': ['slug'],
            },
        ),
    ]
